### PR TITLE
feat: support http protocol

### LINKED ISSUE #31: Use plaintext connection
I'm using this kafka-connect connector with a s3 proxy/gateway that does not support TLS. I think this is the reason why I the following `"Unrecognized SSL message, plaintext connection"` error:

```
[2018-11-09 22:04:40,574] INFO Unable to execute HTTP request: Unrecognized SSL message, plaintext connection? (com.spredfast.shade.amazonaws.http.AmazonHttpClient)
javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at sun.security.ssl.InputRecord.handleUnknownRecord(InputRecord.java:710)
	at sun.security.ssl.InputRecord.read(InputRecord.java:527)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at com.spredfast.shade.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:535)
```

I wonder whether it is possible to **configure the connector to use plaintext** connections instead of using secure connections with TLS.

Thanks.

### PR DESCRIPTION
**Pull request by palmerabollo**
Make S3 protocol configurable (http or https). In some scenarios you might want to use a S3 gateway (e.g. Minio). It's also useful in dev envs.

Resolves #31

### CODE REVIEW

**Comment by cricket007** [comment]
Can't the endpoint parameter be used? This Connect config is working fine for me with Minio

```json
    "__comment": "Minio docker container testing",
    "s3.prefix": "backup-kafka-connect/",
    "s3.path_style": "true",
    "__comment": "Change URL to use external host address",
    "s3.endpoint": "http://localhost:9001"
```

**Comment by palmerabollo** [comment]
Thanks @cricket007. It works.

However I'm still getting this error:

> kafka-connect-65cf98fdb4-rkmbf:kafka-connect Caused by: com.spredfast.shade.amazonaws.AmazonClientException: Unable to verify integrity of data upload.  Client calculated content hash (contentMD5: 88MRqk/dLK+Inz4K+K9g0Q== in base 64) didn't match hash (etag: null in hex) calculated by Amazon S3.  You may need to delete the data stored in Amazon S3. (metadata.contentMD5: 88MRqk/dLK+Inz4K+K9g0Q==, md5DigestStream: null, bucketName: backups-bucket-minio, key: kafka/operations/2019-03-25/operations-00039-000000000000.gz)
> kafka-connect-65cf98fdb4-rkmbf:kafka-connect     at com.spredfast.shade.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1402)

I'm able to fix it updating the AWS SDK jar in the connector, but I don't understand how it can work to you. What version of minio and kafka-connect-s3 are you using?

**Comment by cricket007** [comment]
I've made it work with some 5.x release of Confluent Platform, and some recent versions of Minio. 

There was a blog here - https://blog.minio.io/journaling-kafka-messages-with-s3-connector-and-minio-83651a51045d

I didn't do extensive testing with it, just pointing out that the PR here didn't seem too necessary

**Comment by palmerabollo** [comment]
Thanks. I think it might be working in your scenario because you don't run minio in [gateway mode](https://github.com/minio/minio/tree/master/docs/gateway). I'm closing this PR because the `s3.prefix` solves the issue with the protocol. I'll send another one upgrading the AWS SDK.

Thanks for pointing me out the solution.

**Pull request closed without merging**
